# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: GitHub Package

on:
  workflow_dispatch:
  push:
    branches: [ package ]

jobs:
  package:
    uses: doytowin/doyto-devops/.github/workflows/package.yml@main
    secrets: inherit
    with:
      repo: ${{ github.repository }}
